language: java
services:
  - postgresql
before_script:
  - psql -c 'create user find_driver_dba;' -U postgres
  - psql -c 'create database find_driver_db with owner find_driver_dba;' -U postgres
jdk:
  - oraclejdk8
install:
  ./gradlew assemble
script:
  ./gradlew check
